kind: Job
apiVersion: batch/v1
metadata:
  name: olm-predelete
  namespace: olm
  labels:
    "open-cluster-management.io/addon-pre-delete": ""
  annotations:
    "addon.open-cluster-management.io/addon-pre-delete": ""
spec:
  manualSelector: true
  selector:
    matchLabels:
      job: olm-predelete
  template:
    metadata:
      labels:
        job: olm-predelete
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: olm-operator-serviceaccount
      restartPolicy: Never
      containers:
      - name: cleaner
        image: quay.io/fgiloux/olm-addon-cleaner
        imagePullPolicy: IfNotPresent
        args:
          - "/cleanup.sh"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]